### ISSUE TITLE
Implementation with Google Funding Choices (CMP), which providers to select?

### ISSUE THREAD

**Issue by newssupply** [prebid/prebid-mobile-android#221]
Dear Prebid Team,

I'm trying to implement the Google CMP with prebid, which is working beautifully on your part, but Google has some issues..

When I select all the possible vendors in the UMP (User Managing Platform) a racing concer occurs. 

I'm in contact with Google to resolve this issue, however this usually takes a lot of time, time which most of us dont have because of the new GDPR rules..

So I was wondering if I can make due by only selecting the advertisers listed under the [TCF2 adapters](http://docs.prebid.org/dev-docs/modules/consentManagement.html)?

Not all of the adapters seem to be available in Googles back end, so what happens when a user gives consent for personalized ads but the advertiser is not present in the list, will the advertiser still be able to bid on positions?

please let me know if I need to clarify something, or if I can help in any way!

With kind regards,

Alexander

**Comment by maddapper** [comment]
@newssupply hi Alexander, so when you refer to advertisers, do you mean TCF 2.0 vendors?  Based on my past experience, Funding Choices CMP behaves a little differently than other CMPs.  To avoid race conditions, my suggestion is to put a listener on NSUserDefaults CMP key(s) and then wait 2-3s so that all the TCF string changes can get written.  I will double check with Prebid Mobile team to see when the SDK reads the TCF 2.0 string, it might be that you have to delay the initialization of Prebid SDK until consent is completed.

**Comment by YuriyVelichkoPI** [comment]
@maddapper, is an issue still relevant? 

I'm not sure about the race, because even if consent has been changed during the session it will be updated to the actual value later, so no one should struggle a lot. 

The processing of the bid request respectively to the consent is a duty of each particular bidder. SDK just passes the consent from the device to the Prebid Server. I'm not sure what the bidder should do in the case if it is not present in the list.

**Comment by maddapper** [comment]
@YuriyVelichkoPI yes that should be the case.  I have not heard back from the original bug reporter so I think we can close the issue as it may not be related to Prebid SDK.
