### ISSUE TITLE
Unable to proceed with Google Ad Manager integration

### ISSUE THREAD

**Issue by clho40** [prebid/prebid-mobile-android#581]
Hello,

I'm trying to use GAM as the Primary Ad Server for my mobile app. I followed these guides:

1. https://docs.prebid.org/adops/step-by-step.html
2. https://docs.prebid.org/adops/gam-creative-banner-sbs.html

Only to realize that they were meant for web traffic, not mobile. (Please correct me if I am wrong!)

So I turned to this guide:
https://docs.prebid.org/adops/mobile-rendering-gam-line-item-setup.html

I believe this is the right place for mobile traffic, however, it looks incomplete. How should I proceed after step 3? Where do I get the ad unit id?

Cheers
CL

**Comment by YuriyVelichkoPI** [comment]
Hi @clho40 ! Right, in the result, you are trying incompatible approaches. 

Let me split my answer into two parts. 

-----------------

If you need to integrate with GAM use this guide for the mobile integration: https://docs.prebid.org/prebid-mobile/pbm-api/android/android-sdk-integration-gam-original-api.html

And this guide for the AdOps work: 
- Line Items: https://docs.prebid.org/adops/step-by-step.html
- Creative: https://docs.prebid.org/adops/gam-creative-banner-sbs.html

Don't worry that the guide is for web because it is **universal**. The same setup works for both - web and mobile.  

-----------------

This guide assumes integration with GAM using Rendering API:
https://docs.prebid.org/adops/mobile-rendering-gam-line-item-setup.html

In this case, you should use this guide to setup an order: 
https://docs.prebid.org/adops/mobile-rendering-gam-line-item-setup.html

But you should be 100% sure that you need exactly the Rendering API before using it.

**Comment by clho40** [comment]
Hello, I confirm that it works, here's what I've done:

1. https://docs.prebid.org/adops/step-by-step.html
2. https://docs.prebid.org/adops/gam-creative-banner-sbs.html
3. Create an ad unit on GAM. View the Ad Unit, go to Tags, generate a `Mobile Application Tag` and we should get something like `/123456778/prebid-banner-1`
4. Follow https://docs.prebid.org/prebid-mobile/modules/rendering/android-sdk-integration-gam.html and use the ad unit ID from above and VOLA. 

Cheers!
