### ISSUE TITLE
NullPointerException in UserConsentManager

### ISSUE THREAD

**Issue by linean** [prebid/prebid-mobile-android#633]
**Describe the bug**
Some of our production users are experiencing a crash related to Prebid UserConsentManager. Unfortunately we are not able to reproduce it but maybe stack-trace can help you to identify the root cause.

**Stack-trace**
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.prebid.mobile.rendering.sdk.deviceData.managers.UserConsentManager.v()' on a null object reference
       at org.prebid.mobile.rendering.networking.modelcontrollers.Requester.getAdId(Requester.java:127)
       at org.prebid.mobile.rendering.networking.modelcontrollers.BidRequester.startAdRequest(BidRequester.java:43)
       at org.prebid.mobile.rendering.bidding.loader.BidLoader.sendBidRequest(BidLoader.java:194)
       at org.prebid.mobile.rendering.bidding.loader.BidLoader.load(BidLoader.java:145)
       at org.prebid.mobile.api.mediation.MediationBaseAdUnit.fetchDemand(MediationBaseAdUnit.java:107)
       at org.prebid.mobile.api.mediation.MediationBannerAdUnit.fetchDemand(MediationBannerAdUnit.java:87)
       at our code...
```

**SDK Version**
 - org.prebid:prebid-mobile-sdk:2.1.0
 - org.prebid:prebid-mobile-sdk-max-adapters:2.1.0

**Comment by ValentinPostindustria** [comment]
Hi. We think that we found the reason for the crash. It seems that SDK initialization fails for some reason and the mediation ad units try to work with it. We will fix the crash, but we need to know the reason for the failed initialization. 
- Do you use `PrebidMobile.initializeSdk()`? 
- When you create any `MediationAdUnit` instance do you get any logs about the initialization problems? Because MediationAdUnits initializes the Prebid SDK when you create them. Log tag `PrebidMobile`. 
- What percentage of users get this crash? Maybe it is only on a specific version of Android?  


### Steps to reproduce the crash in Kotlin Demo app. 

- Comment out the initialization of the Applovin and AdMob SDKs, because they initialize Prebid SDK in the adapters:
```
// initAdMob()
// initApplovinMax()
```

- Comment out the initialization:
```
// PrebidMobile.initializeSdk(applicationContext) { ... }
```

- Emulate failed initialization in `MediationBaseAdUnit`:
```
initSdk(null);
```

- Open any AdMob example. 


### Solution for crash

The mediation ad units don't check if the SDK was initialized, so if a user runs a mediation ad unit when the SDK initialization wasn't called or it failed it causes the crash. We need to add the checks if the SDK was initialized. 

The original API ad units check it using Context that is initialized only during the SDK initialization. But other ad units use the Context provided by a user as a parameter to the ad unit.

**Comment by linean** [comment]
Hi Valentin. It looks like something caused a spike in this crash two days ago and now it's completely gone 🤷 

> Do you use PrebidMobile.initializeSdk()

No. We don't call it manually.

> When you create any MediationAdUnit instance do you get any logs about the initialization problems? Because MediationAdUnits initializes the Prebid SDK when you create them. Log tag PrebidMobile.

Unfortunately I don't have any prebid logs from the moment this crash occurred. 

> What percentage of users get this crash? Maybe it is only on a specific version of Android?

Spike affected insignificant number of users. Most of them from Android 7, but there are some occurrences from other versions for e.g. Android 11.
